# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: new-client-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'new-client-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18new-client-service.proto\x12\tnewClient\"\x7f\n\x10NewClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0brouting_key\x18\x02 \x01(\t\x12!\n\x19outputs_queue_calibration\x18\x03 \x01(\t\x12 \n\x18inputs_queue_calibration\x18\x04 \x01(\t\"4\n\x11NewClientResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb7\x01\n\x19\x43lientNotificationService\x12L\n\x0fNotifyNewClient\x12\x1b.newClient.NewClientRequest\x1a\x1c.newClient.NewClientResponse\x12L\n\x0bHealthCheck\x12\x1d.newClient.HealthCheckRequest\x1a\x1e.newClient.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'new_client_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWCLIENTREQUEST']._serialized_start=39
  _globals['_NEWCLIENTREQUEST']._serialized_end=166
  _globals['_NEWCLIENTRESPONSE']._serialized_start=168
  _globals['_NEWCLIENTRESPONSE']._serialized_end=220
  _globals['_HEALTHCHECKREQUEST']._serialized_start=222
  _globals['_HEALTHCHECKREQUEST']._serialized_end=242
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=244
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=298
  _globals['_CLIENTNOTIFICATIONSERVICE']._serialized_start=301
  _globals['_CLIENTNOTIFICATIONSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
